package core.blog.control;

import java.math.BigDecimal;

public class RecordLoanFee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.user_gid
     *
     * @mbggenerated
     */
    private String userGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.fee
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.loan_rate
     *
     * @mbggenerated
     */
    private BigDecimal loanRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.aisle_fee
     *
     * @mbggenerated
     */
    private BigDecimal aisleFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.aisle_rate
     *
     * @mbggenerated
     */
    private BigDecimal aisleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.credit_fee
     *
     * @mbggenerated
     */
    private BigDecimal creditFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.credit_rate
     *
     * @mbggenerated
     */
    private BigDecimal creditRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.platform_fee
     *
     * @mbggenerated
     */
    private BigDecimal platformFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.platform_rate
     *
     * @mbggenerated
     */
    private BigDecimal platformRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.risk_intend_fee
     *
     * @mbggenerated
     */
    private BigDecimal riskIntendFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.check_fee
     *
     * @mbggenerated
     */
    private BigDecimal checkFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.check_rate
     *
     * @mbggenerated
     */
    private BigDecimal checkRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.profit_fee
     *
     * @mbggenerated
     */
    private BigDecimal profitFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.profit_rate
     *
     * @mbggenerated
     */
    private BigDecimal profitRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.customer_fee
     *
     * @mbggenerated
     */
    private BigDecimal customerFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.customer_rate
     *
     * @mbggenerated
     */
    private BigDecimal customerRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.fee1
     *
     * @mbggenerated
     */
    private BigDecimal fee1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.rate1
     *
     * @mbggenerated
     */
    private BigDecimal rate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.fee2
     *
     * @mbggenerated
     */
    private BigDecimal fee2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.rate2
     *
     * @mbggenerated
     */
    private BigDecimal rate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.fee3
     *
     * @mbggenerated
     */
    private BigDecimal fee3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.rate3
     *
     * @mbggenerated
     */
    private BigDecimal rate3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.voucher_amount
     *
     * @mbggenerated
     */
    private BigDecimal voucherAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.biz_type
     *
     * @mbggenerated
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_loan_fee.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.id
     *
     * @return the value of record_loan_fee.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.id
     *
     * @param id the value for record_loan_fee.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.gid
     *
     * @return the value of record_loan_fee.gid
     *
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.gid
     *
     * @param gid the value for record_loan_fee.gid
     *
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.create_time
     *
     * @return the value of record_loan_fee.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.create_time
     *
     * @param createTime the value for record_loan_fee.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.update_time
     *
     * @return the value of record_loan_fee.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.update_time
     *
     * @param updateTime the value for record_loan_fee.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.user_gid
     *
     * @return the value of record_loan_fee.user_gid
     *
     * @mbggenerated
     */
    public String getUserGid() {
        return userGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.user_gid
     *
     * @param userGid the value for record_loan_fee.user_gid
     *
     * @mbggenerated
     */
    public void setUserGid(String userGid) {
        this.userGid = userGid == null ? null : userGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.fee
     *
     * @return the value of record_loan_fee.fee
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.fee
     *
     * @param fee the value for record_loan_fee.fee
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.loan_rate
     *
     * @return the value of record_loan_fee.loan_rate
     *
     * @mbggenerated
     */
    public BigDecimal getLoanRate() {
        return loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.loan_rate
     *
     * @param loanRate the value for record_loan_fee.loan_rate
     *
     * @mbggenerated
     */
    public void setLoanRate(BigDecimal loanRate) {
        this.loanRate = loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.aisle_fee
     *
     * @return the value of record_loan_fee.aisle_fee
     *
     * @mbggenerated
     */
    public BigDecimal getAisleFee() {
        return aisleFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.aisle_fee
     *
     * @param aisleFee the value for record_loan_fee.aisle_fee
     *
     * @mbggenerated
     */
    public void setAisleFee(BigDecimal aisleFee) {
        this.aisleFee = aisleFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.aisle_rate
     *
     * @return the value of record_loan_fee.aisle_rate
     *
     * @mbggenerated
     */
    public BigDecimal getAisleRate() {
        return aisleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.aisle_rate
     *
     * @param aisleRate the value for record_loan_fee.aisle_rate
     *
     * @mbggenerated
     */
    public void setAisleRate(BigDecimal aisleRate) {
        this.aisleRate = aisleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.credit_fee
     *
     * @return the value of record_loan_fee.credit_fee
     *
     * @mbggenerated
     */
    public BigDecimal getCreditFee() {
        return creditFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.credit_fee
     *
     * @param creditFee the value for record_loan_fee.credit_fee
     *
     * @mbggenerated
     */
    public void setCreditFee(BigDecimal creditFee) {
        this.creditFee = creditFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.credit_rate
     *
     * @return the value of record_loan_fee.credit_rate
     *
     * @mbggenerated
     */
    public BigDecimal getCreditRate() {
        return creditRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.credit_rate
     *
     * @param creditRate the value for record_loan_fee.credit_rate
     *
     * @mbggenerated
     */
    public void setCreditRate(BigDecimal creditRate) {
        this.creditRate = creditRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.platform_fee
     *
     * @return the value of record_loan_fee.platform_fee
     *
     * @mbggenerated
     */
    public BigDecimal getPlatformFee() {
        return platformFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.platform_fee
     *
     * @param platformFee the value for record_loan_fee.platform_fee
     *
     * @mbggenerated
     */
    public void setPlatformFee(BigDecimal platformFee) {
        this.platformFee = platformFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.platform_rate
     *
     * @return the value of record_loan_fee.platform_rate
     *
     * @mbggenerated
     */
    public BigDecimal getPlatformRate() {
        return platformRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.platform_rate
     *
     * @param platformRate the value for record_loan_fee.platform_rate
     *
     * @mbggenerated
     */
    public void setPlatformRate(BigDecimal platformRate) {
        this.platformRate = platformRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.risk_intend_fee
     *
     * @return the value of record_loan_fee.risk_intend_fee
     *
     * @mbggenerated
     */
    public BigDecimal getRiskIntendFee() {
        return riskIntendFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.risk_intend_fee
     *
     * @param riskIntendFee the value for record_loan_fee.risk_intend_fee
     *
     * @mbggenerated
     */
    public void setRiskIntendFee(BigDecimal riskIntendFee) {
        this.riskIntendFee = riskIntendFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.check_fee
     *
     * @return the value of record_loan_fee.check_fee
     *
     * @mbggenerated
     */
    public BigDecimal getCheckFee() {
        return checkFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.check_fee
     *
     * @param checkFee the value for record_loan_fee.check_fee
     *
     * @mbggenerated
     */
    public void setCheckFee(BigDecimal checkFee) {
        this.checkFee = checkFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.check_rate
     *
     * @return the value of record_loan_fee.check_rate
     *
     * @mbggenerated
     */
    public BigDecimal getCheckRate() {
        return checkRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.check_rate
     *
     * @param checkRate the value for record_loan_fee.check_rate
     *
     * @mbggenerated
     */
    public void setCheckRate(BigDecimal checkRate) {
        this.checkRate = checkRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.profit_fee
     *
     * @return the value of record_loan_fee.profit_fee
     *
     * @mbggenerated
     */
    public BigDecimal getProfitFee() {
        return profitFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.profit_fee
     *
     * @param profitFee the value for record_loan_fee.profit_fee
     *
     * @mbggenerated
     */
    public void setProfitFee(BigDecimal profitFee) {
        this.profitFee = profitFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.profit_rate
     *
     * @return the value of record_loan_fee.profit_rate
     *
     * @mbggenerated
     */
    public BigDecimal getProfitRate() {
        return profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.profit_rate
     *
     * @param profitRate the value for record_loan_fee.profit_rate
     *
     * @mbggenerated
     */
    public void setProfitRate(BigDecimal profitRate) {
        this.profitRate = profitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.customer_fee
     *
     * @return the value of record_loan_fee.customer_fee
     *
     * @mbggenerated
     */
    public BigDecimal getCustomerFee() {
        return customerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.customer_fee
     *
     * @param customerFee the value for record_loan_fee.customer_fee
     *
     * @mbggenerated
     */
    public void setCustomerFee(BigDecimal customerFee) {
        this.customerFee = customerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.customer_rate
     *
     * @return the value of record_loan_fee.customer_rate
     *
     * @mbggenerated
     */
    public BigDecimal getCustomerRate() {
        return customerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.customer_rate
     *
     * @param customerRate the value for record_loan_fee.customer_rate
     *
     * @mbggenerated
     */
    public void setCustomerRate(BigDecimal customerRate) {
        this.customerRate = customerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.fee1
     *
     * @return the value of record_loan_fee.fee1
     *
     * @mbggenerated
     */
    public BigDecimal getFee1() {
        return fee1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.fee1
     *
     * @param fee1 the value for record_loan_fee.fee1
     *
     * @mbggenerated
     */
    public void setFee1(BigDecimal fee1) {
        this.fee1 = fee1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.rate1
     *
     * @return the value of record_loan_fee.rate1
     *
     * @mbggenerated
     */
    public BigDecimal getRate1() {
        return rate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.rate1
     *
     * @param rate1 the value for record_loan_fee.rate1
     *
     * @mbggenerated
     */
    public void setRate1(BigDecimal rate1) {
        this.rate1 = rate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.fee2
     *
     * @return the value of record_loan_fee.fee2
     *
     * @mbggenerated
     */
    public BigDecimal getFee2() {
        return fee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.fee2
     *
     * @param fee2 the value for record_loan_fee.fee2
     *
     * @mbggenerated
     */
    public void setFee2(BigDecimal fee2) {
        this.fee2 = fee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.rate2
     *
     * @return the value of record_loan_fee.rate2
     *
     * @mbggenerated
     */
    public BigDecimal getRate2() {
        return rate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.rate2
     *
     * @param rate2 the value for record_loan_fee.rate2
     *
     * @mbggenerated
     */
    public void setRate2(BigDecimal rate2) {
        this.rate2 = rate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.fee3
     *
     * @return the value of record_loan_fee.fee3
     *
     * @mbggenerated
     */
    public BigDecimal getFee3() {
        return fee3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.fee3
     *
     * @param fee3 the value for record_loan_fee.fee3
     *
     * @mbggenerated
     */
    public void setFee3(BigDecimal fee3) {
        this.fee3 = fee3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.rate3
     *
     * @return the value of record_loan_fee.rate3
     *
     * @mbggenerated
     */
    public BigDecimal getRate3() {
        return rate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.rate3
     *
     * @param rate3 the value for record_loan_fee.rate3
     *
     * @mbggenerated
     */
    public void setRate3(BigDecimal rate3) {
        this.rate3 = rate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.voucher_amount
     *
     * @return the value of record_loan_fee.voucher_amount
     *
     * @mbggenerated
     */
    public BigDecimal getVoucherAmount() {
        return voucherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.voucher_amount
     *
     * @param voucherAmount the value for record_loan_fee.voucher_amount
     *
     * @mbggenerated
     */
    public void setVoucherAmount(BigDecimal voucherAmount) {
        this.voucherAmount = voucherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.biz_type
     *
     * @return the value of record_loan_fee.biz_type
     *
     * @mbggenerated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.biz_type
     *
     * @param bizType the value for record_loan_fee.biz_type
     *
     * @mbggenerated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_loan_fee.remark
     *
     * @return the value of record_loan_fee.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_loan_fee.remark
     *
     * @param remark the value for record_loan_fee.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "RecordLoanFee{" +
                "id=" + id +
                ", gid='" + gid + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", userGid='" + userGid + '\'' +
                ", fee=" + fee +
                ", loanRate=" + loanRate +
                ", aisleFee=" + aisleFee +
                ", aisleRate=" + aisleRate +
                ", creditFee=" + creditFee +
                ", creditRate=" + creditRate +
                ", platformFee=" + platformFee +
                ", platformRate=" + platformRate +
                ", riskIntendFee=" + riskIntendFee +
                ", checkFee=" + checkFee +
                ", checkRate=" + checkRate +
                ", profitFee=" + profitFee +
                ", profitRate=" + profitRate +
                ", customerFee=" + customerFee +
                ", customerRate=" + customerRate +
                ", fee1=" + fee1 +
                ", rate1=" + rate1 +
                ", fee2=" + fee2 +
                ", rate2=" + rate2 +
                ", fee3=" + fee3 +
                ", rate3=" + rate3 +
                ", voucherAmount=" + voucherAmount +
                ", bizType='" + bizType + '\'' +
                ", remark='" + remark + '\'' +
                '}';
    }
}